name: bmi_calculator
description: An application to calculate BMI.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^10.2.1

dev_dependencies:
  alchemist: ^0.5.1
  flutter_driver:
    sdk: flutter

  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  test: any
  very_good_analysis: ^3.0.2

flutter:

  uses-material-design: true
