name: bmi_calculator
description: An application to calculate BMI

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^9.2.0

dev_dependencies:
  flutter_driver:
    sdk: flutter

  flutter_test:
    sdk: flutter

  test: any
  very_good_analysis: ^2.4.0

flutter:

  uses-material-design: true
