name: bmi_calculator

on: [pull_request]

jobs:
  tests:
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Flutter action
      uses: subosito/flutter-action@v1.5.3
   
    - name: Install dependencies
      run: flutter pub get

    - name: Format
      run: flutter format --set-exit-if-changed lib test

    - name: Run tests
      run: flutter test --no-pub --coverage --test-randomize-ordering-seed random --exclude-tags='no-ci'

    - name: Very Good Coverage
      uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
