name: bmi_calculator

on: [pull_request]

jobs:
  tests:
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Flutter action
      uses: subosito/flutter-action@v2.4.0
   
    - name: Install dependencies
      run: flutter pub get

    - name: Format
      run: flutter format --set-exit-if-changed lib test

    - name: Run tests
      run: flutter test --no-pub --coverage --test-randomize-ordering-seed random --exclude-tags='no-ci'

    - name: Very Good Coverage
      uses: VeryGoodOpenSource/very_good_coverage@v1.2.1

    - name: Upload coverage to codecov
    - uses: actions/checkout@main
    - uses: codecov/codecov-action@v2
      with:
        files: ./coverage/lcov.info # optional
        flags: unittests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
        path_to_write_report: ./coverage/codecov_report.txt
